# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d8c02d91469a4e05a42df3ec17b5b239870c0d146495d9ec9d8e6e47fe0e8f3c8bc7003a8a065288ca566ce45764c0b51d022306da8232e6c9deba1ec829777

test:
  secret_key_base: a9add8e5cbbaed2bbb2dbd269b25095bb94a9e32f825063de2dadd2a555989b0a8e7797eb631089cd62ac9dc313f9721946062e44f24b3f6fc4a0f3d3a54ede0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
 # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
 secret_key_base: e2c398072d19e860ec73c95bcc792776e212eaf913a51379940df17bf6a5a5b986bf48a427798a6e77e4e0141a5bacfcabe664eafbb3bbddf54710eee6e5c8b8	
